services:
  - type: web
    name: pfe-api
    runtime: python
    repo: https://github.com/islem-hkiri/pfe-api/tree/master  # Change avec ton repo
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn api_local_websocket:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0